{
 "title": "Node Dashboard",
 "description": "Some metrics values exported by Prometheus and Node Exporter.",
 "tags": [
  "prometheus",
  "node_exporter"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_boot_time_seconds, instance)"
   },
   {
    "name": "device",
    "label": "Network_Device",
    "query": "label_values(node_network_receive_bytes_total, device)"
   },
   { "name": "mountpoint", "label": "Mountpoint", "query": { "query": "label_values(mountpoint)" } },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Prometheus Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, max(scrape_duration_seconds) by (job))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Node Temps",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by (job) (node_hwmon_temp_celsius{ })",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available Memory & Load for Node : ${node}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "Available memory",
   "type": "stat",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "( (node_memory_MemFree_bytes{instance=~\"$node\"} + node_memory_Cached_bytes{instance=~\"$node\"} + node_memory_Slab_bytes{instance=~\"$node\"} + node_memory_Buffers_bytes{instance=~\"$node\"} ) / node_memory_MemTotal_bytes{instance=~\"$node\"}) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"} / count by(job, instance)(count by(job, instance, cpu)(node_cpu_seconds_total{instance=~\"$node\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU, MEM, and Disk Info for Node : ${node}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 }
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$node\"}) / count(count(node_cpu_seconds_total{instance=~\"$node\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (CPU) (node_cpu_seconds_total{instance=~\"$node\"}) / 8)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - avg(((node_memory_MemAvailable_bytes{instance=~\"$node\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$node\"}))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min((node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=~\"$node\"} - node_filesystem_free_bytes{fstype=~\"xfs|ext4\",instance=~\"$node\"} )/ node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total RootFS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"$node\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "System Load (1m avg)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total SWAP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_SwapTotal_bytes{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Disk Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"$node\", device=~\"/dev/.*\"})"
    }
   ]
  },
  {
   "title": "CPU System Load (5m avg)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=~\"$node\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(((node_memory_SwapTotal_bytes{instance=~\"$node\"} - node_memory_SwapFree_bytes{instance=~\"$node\"}) / (node_memory_SwapTotal_bytes{instance=~\"$node\"} ))) * 100"
    }
   ]
  },
  {
   "title": "Used Root FS",
   "type": "gauge",
   "description": "The root filesystem is the filesystem that is contained on the same partition on which the root directory is located",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - avg(((node_filesystem_avail_bytes{instance=~\"$node\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$node\",mountpoint=\"/\",fstype!=\"rootfs\"}))"
    }
   ]
  },
  {
   "title": "System Load (5m avg)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Uptime (Average for all)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_time_seconds{instance=~\"$node\"} - node_boot_time_seconds{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "CPU, MEM, and Load Graphs for Node : ${node}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 }
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_load1{instance=~\"$node\"})",
     "legendFormat": "1m load average"
    },
    {
     "expr": "sum(node_load5{instance=~\"$node\"})",
     "legendFormat": "5m load average"
    },
    {
     "expr": "sum(node_load15{instance=~\"$node\"})",
     "legendFormat": "15m load average"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode!=\"idle\",mode!=\"irq\",mode!=\"nice\",mode!=\"softirq\",mode!=\"steal\",mode!=\"system\",mode!=\"user\"}[$__rate_interval]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode!=\"idle\",mode!=\"iowait\",mode!=\"nice\",mode!=\"softirq\",mode!=\"steal\",mode!=\"system\",mode!=\"user\"}[$__rate_interval]))",
     "legendFormat": "irq"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode!=\"idle\",mode!=\"iowait\",mode!=\"irq\",mode!=\"softirq\",mode!=\"steal\",mode!=\"system\",mode!=\"user\"}[$__rate_interval]))",
     "legendFormat": "nice"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode!=\"idle\",mode!=\"iowait\",mode!=\"irq\",mode!=\"nice\",mode!=\"steal\",mode!=\"system\",mode!=\"user\"}[$__rate_interval]))",
     "legendFormat": "softirq"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode!=\"idle\",mode!=\"iowait\",mode!=\"irq\",mode!=\"nice\",mode!=\"softirq\",mode!=\"system\",mode!=\"user\"}[$__rate_interval]))",
     "legendFormat": "steal"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode!=\"idle\",mode!=\"iowait\",mode!=\"irq\",mode!=\"nice\",mode!=\"softirq\",mode!=\"steal\",mode!=\"user\"}[$__rate_interval]))",
     "legendFormat": "system"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode!=\"idle\",mode!=\"iowait\",mode!=\"irq\",mode!=\"nice\",mode!=\"softirq\",mode!=\"steal\",mode!=\"system\"}[$__rate_interval]))",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"})",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "sum(node_memory_Cached_bytes{instance=~\"$node\"} + node_memory_Buffers_bytes{instance=~\"$node\"})",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "sum(node_memory_MemFree_bytes{instance=~\"$node\"})",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "sum((node_memory_SwapTotal_bytes{instance=~\"$node\"} - node_memory_SwapFree_bytes{instance=~\"$node\"}))",
     "legendFormat": "SWAP Used"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemFree_bytes{instance=~\"$node\"} - (node_memory_Cached_bytes{instance=~\"$node\"} + node_memory_Buffers_bytes{instance=~\"$node\"}))",
     "legendFormat": "RAM Used"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "System"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='user',instance=~\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "User "
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='nice',instance=~\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "Nice"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "Iowait"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='irq',instance=~\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "Irq"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='softirq',instance=~\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "Softirq"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='steal',instance=~\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "Steal"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='guest',instance=~\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "Guest"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemFree_bytes{instance=~\"$node\"} - node_memory_Buffers_bytes{instance=~\"$node\"} - node_memory_Cached_bytes{instance=~\"$node\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg(node_memory_Buffers_bytes{instance=~\"$node\"})",
     "legendFormat": "Buffers"
    },
    {
     "expr": "avg(node_memory_Cached_bytes{instance=~\"$node\"})",
     "legendFormat": "Cached"
    },
    {
     "expr": "avg(node_memory_MemFree_bytes{instance=~\"$node\"})",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemFree_bytes{instance=~\"$node\"} - node_memory_Buffers_bytes{instance=~\"$node\"} - node_memory_Cached_bytes{instance=~\"$node\"} - node_memory_Slab_bytes{instance=~\"$node\"} - node_memory_PageTables_bytes{instance=~\"$node\"} - node_memory_SwapCached_bytes{instance=~\"$node\"})",
     "legendFormat": "Apps"
    },
    {
     "expr": "avg(node_memory_PageTables_bytes{instance=~\"$node\"})",
     "legendFormat": "PageTables"
    },
    {
     "expr": "avg(node_memory_SwapCached_bytes{instance=~\"$node\"})",
     "legendFormat": "SwapCache"
    },
    {
     "expr": "avg(node_memory_Slab_bytes{instance=~\"$node\"})",
     "legendFormat": "Slab"
    },
    {
     "expr": "avg(node_memory_Cached_bytes{instance=~\"$node\"})",
     "legendFormat": "Cache"
    },
    {
     "expr": "avg(node_memory_Buffers_bytes{instance=~\"$node\"})",
     "legendFormat": "Buffers"
    },
    {
     "expr": "avg(node_memory_MemFree_bytes{instance=~\"$node\"})",
     "legendFormat": "Unused"
    },
    {
     "expr": "avg((node_memory_SwapTotal_bytes{instance=~\"$node\"} - node_memory_SwapFree_bytes{instance=~\"$node\"}))",
     "legendFormat": "Swap"
    },
    {
     "expr": "avg(node_memory_HardwareCorrupted_bytes{instance=~\"$node\"})",
     "legendFormat": "Harware Corrupted"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"system\",instance=~\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode='user',instance=~\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode='iowait',instance=~\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\"$node\",job=~\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Disk Graphs for Node : ${node} , Disk : ${mountpoint}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 }
  },
  {
   "title": "Disk Space Used",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$node\",device!~'rootfs',mountpoint!~'/run.*',mountpoint=~\"$mountpoint\"} - node_filesystem_avail_bytes{instance=~\"$node\",device!~'rootfs',mountpoint!~'/run.*',mountpoint=~\"$mountpoint\"}",
     "legendFormat": "{{instance}} {{mountpoint}}"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "- sum(irate(node_disk_written_bytes_total{instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Written"
    }
   ]
  },
  {
   "title": "Disk Space Utilization",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - node_filesystem_free_bytes{instance=~\"$node\",fstype!='rootfs',mountpoint=~\"$mountpoint\",mountpoint!~'/run.*'} / node_filesystem_size_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}} {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network Overview for Node : ${node}, Network Device : $device",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 }
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device=~\"$device\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "TX"
    },
    {
     "expr": "- sum(irate(node_network_receive_bytes_total{device=~\"$device\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "Total Traffic In",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device=~\"$device\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Traffic Out",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device=~\"$device\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Netstat: TCP",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_netstat_Tcp_ActiveOpens{instance=~\"$node\"})",
     "legendFormat": "ActiveOpens"
    },
    {
     "expr": "sum(node_netstat_Tcp_CurrEstab{instance=~\"$node\"})",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "sum(node_netstat_Tcp_InErrs{instance=~\"$node\"})",
     "legendFormat": "InErrs"
    },
    {
     "expr": "sum(node_netstat_Tcp_InSegs{instance=~\"$node\"})\n",
     "legendFormat": "InSegs"
    },
    {
     "expr": "sum(node_netstat_Tcp_OutRsts{instance=~\"$node\"})\n",
     "legendFormat": "OutRsts"
    },
    {
     "expr": "sum(node_netstat_Tcp_OutSegs{instance=~\"$node\"})",
     "legendFormat": "OutSegs"
    },
    {
     "expr": "sum(node_netstat_Tcp_PassiveOpens{instance=~\"$node\"})",
     "legendFormat": "PassiveOpens"
    },
    {
     "expr": "sum(node_netstat_Tcp_RetransSegs{instance=~\"$node\"})",
     "legendFormat": "RetransSegs"
    }
   ]
  },
  {
   "title": "Netstat: UDP",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_netstat_Udp_InDatagrams{instance=~\"$node\"})",
     "legendFormat": "InDatagrams"
    },
    {
     "expr": "sum(node_netstat_Udp_InErrors{instance=~\"$node\"})",
     "legendFormat": "InErrors"
    },
    {
     "expr": "sum(node_netstat_Udp_NoPorts{instance=~\"$node\"})",
     "legendFormat": "NoPorts"
    },
    {
     "expr": "sum(node_netstat_Udp_OutDatagrams{instance=~\"$node\"})",
     "legendFormat": "OutDatagrams"
    },
    {
     "expr": "sum(node_netstat_Udp_RcvbufErrors{instance=~\"$node\"})",
     "legendFormat": "RcvbufErrors"
    },
    {
     "expr": "sum(node_netstat_Udp_SndbufErrors{instance=~\"$node\"})",
     "legendFormat": "SndbufErrors"
    }
   ]
  },
  {
   "title": "Network Traffic Detail for Node : ${node}, Network Device : $device",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 }
  },
  {
   "title": "Network Traffic by Packets",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_packets_total{instance=~\"$node\",device=~\"$device\"}[$__rate_interval]))",
     "legendFormat": "TX"
    },
    {
     "expr": "- sum(irate(node_network_receive_packets_total{instance=~\"$node\",device=~\"$device\"}[$__rate_interval]))",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{instance=~\"$node\",device=~\"$device\"}[$__rate_interval]))",
     "legendFormat": "TX"
    },
    {
     "expr": "- sum(irate(node_network_receive_bytes_total{instance=~\"$node\",device=~\"$device\"}[$__rate_interval]))",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "Network Traffic Drop",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_drop_total{instance=~\"$node\",device=~\"$device\"}[$__rate_interval]))",
     "legendFormat": "TX"
    },
    {
     "expr": "- sum(irate(node_network_receive_drop_total{instance=~\"$node\",device=~\"$device\"}[$__rate_interval]))",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "Network Traffic Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_errs_total{instance=~\"$node\",device=~\"$device\"}[$__rate_interval]))",
     "legendFormat": "TX"
    },
    {
     "expr": "- sum(irate(node_network_receive_errs_total{instance=~\"$node\",device=~\"$device\"}[$__rate_interval]))",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_netstat_Tcp_CurrEstab{instance=~\"$node\"})",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "sum(node_netstat_Tcp_InErrs{instance=~\"$node\"})",
     "legendFormat": "InErrs"
    }
   ]
  },
  {
   "title": "Network Traffic Fifo",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_fifo_total{instance=~\"$node\",device=~\"$device\"}[$__rate_interval]))",
     "legendFormat": "TX FIFO"
    },
    {
     "expr": "- sum(irate(node_network_receive_fifo_total{instance=~\"$node\",device=~\"$device\"}[$__rate_interval]))",
     "legendFormat": "RX FIFO"
    }
   ]
  }
 ]
}