{
 "title": "OPNSense",
 "description": "OPNSense metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job Name",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   { "name": "wan_interface", "label": "WAN Interface(s)", "query": { "query": "label_values(device)" } },
   { "name": "lan_interface", "label": "LAN Interface(s)", "query": { "query": "label_values(device)" } },
   { "name": "wg_interface", "label": "WG Interface(s)", "query": { "query": "label_values(device)" } },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "System Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Available Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_free_bytes{job=\"$job\"} + node_memory_inactive_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"$job\"} - node_boot_time_seconds{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{job=\"$job\",mode=\"idle\"}[1m])) * 100 / scalar(count(node_cpu_seconds_total{job=\"$job\",mode=\"user\"}))"
    }
   ]
  },
  {
   "title": "Free Swap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_swap_size_bytes{job=\"$job\"} - node_memory_swap_used_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_exec_forks_total{job=\"$job\"}",
     "legendFormat": "Forks"
    },
    {
     "expr": "node_exec_system_calls_total{job=\"$job\"}",
     "legendFormat": "System Calls"
    },
    {
     "expr": "node_exec_traps_total{job=\"$job\"}",
     "legendFormat": "Traps"
    }
   ]
  },
  {
   "title": "🔥 CPU Temp",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_cpu_temperature_celsius{job=\"$job\",cpu=~\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_exec_device_interrupts_total{job=\"$job\"}[5m])",
     "legendFormat": "interrupts"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_exec_context_switches_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🛠️ System Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{job=\"$job\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{job=\"$job\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{job=\"$job\"}",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_active_bytes{job=\"$job\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_buffer_bytes{job=\"$job\"}",
     "legendFormat": "Buffer"
    },
    {
     "expr": "node_memory_cache_bytes{job=\"$job\"}",
     "legendFormat": "Cache"
    },
    {
     "expr": "node_memory_free_bytes{job=\"$job\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_inactive_bytes{job=\"$job\"}",
     "legendFormat": "Inactive"
    },
    {
     "expr": "node_memory_laundry_bytes{job=\"$job\"}",
     "legendFormat": "Laundry"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{job=\"$job\"}[1m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{job=\"$job\",mode=\"user\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_swap_used_bytes{job=\"$job\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_swap_size_bytes{job=\"$job\"} - node_memory_swap_in_bytes_total{job=\"$job\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_swap_size_bytes{job=\"$job\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_cpu_temperature_celsius{job=\"$job\",cpu=~\"0\"}",
     "legendFormat": "CPU: {{cpu}}"
    }
   ]
  },
  { "title": "Network Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "🔽 WAN IN (igc4)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=~\"$job\",device=~\"igc4\"}[$__rate_interval])*8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🔼 WAN OUT (igc4)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=~\"$job\",device=~\"igc4\"}[$__rate_interval])*8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Net pkts/sec",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_packets_total{job=\"$job\"}[$__interval]) +  rate(node_network_transmit_packets_total{job=\"$job\"}[$__interval])) > 0"
    }
   ]
  },
  {
   "title": "📶 Traffic / hour (igc4)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{job=\"$job\",device=\"igc4\"}[60m])",
     "legendFormat": "{{device}}_Tx"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{job=\"$job\",device=\"igc4\"}[60m])",
     "legendFormat": "{{device}}_Rx"
    }
   ]
  },
  {
   "title": "WAN In/Out",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"$job\",device=~\"$wan_interface\"}[1m])",
     "legendFormat": "In: {{device}}"
    },
    {
     "expr": "-irate(node_network_transmit_bytes_total{job=\"$job\",device=~\"$wan_interface\"}[1m])",
     "legendFormat": "Out: {{device}}"
    }
   ]
  },
  {
   "title": "LAN In/Out",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"$job\",device=~\"$lan_interface\"}[1m])",
     "legendFormat": "In: {{ device }}"
    },
    {
     "expr": "-irate(node_network_transmit_bytes_total{job=\"$job\",device=~\"$lan_interface\"}[1m])",
     "legendFormat": "Out: {{ device }}"
    }
   ]
  },
  {
   "title": "WAN Transmit Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets_total{job=\"$job\",device=~\"$wan_interface\"}[1m])",
     "legendFormat": "Transmit: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_multicast_total{job=\"$job\",device=~\"$wan_interface\"}[1m])",
     "legendFormat": "Multicasts: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{job=\"$job\",device=~\"$wan_interface\"}[1m])",
     "legendFormat": "Drops: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{job=\"$job\",device=~\"$wan_interface\"}[1m])",
     "legendFormat": "Errors: {{ device }}"
    }
   ]
  },
  {
   "title": "LAN Transmit Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets_total{job=\"$job\",device=~\"$lan_interface\"}[1m])",
     "legendFormat": "Transmit {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_multicast_total{job=\"$job\",device=~\"$lan_interface\"}[1m])",
     "legendFormat": "Multicasts: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{job=\"$job\",device=~\"$lan_interface\"}[1m])",
     "legendFormat": "Drops: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{job=\"$job\",device=~\"$lan_interface\"}[1m])",
     "legendFormat": "Errors: {{ device }}"
    }
   ]
  },
  {
   "title": "WAN Receive Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{job=\"$job\",device=~\"$wan_interface\"}[1m])",
     "legendFormat": "Receive: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_multicast_total{job=\"$job\",device=~\"$wan_interface\"}[1m])",
     "legendFormat": "Multicasts: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_drop_total{job=\"$job\",device=~\"$wan_interface\"}[1m])",
     "legendFormat": "Drops: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_errs_total{job=\"$job\",device=~\"$wan_interface\"}[1m])",
     "legendFormat": "Errors: {{ device }}"
    }
   ]
  },
  {
   "title": "LAN Receive Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{job=\"$job\",device=~\"$lan_interface\"}[1m])",
     "legendFormat": "Receive: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_multicast_total{job=\"$job\",device=~\"$lan_interface\"}[1m])",
     "legendFormat": "Multicasts: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_drop_total{job=\"$job\",device=~\"$lan_interface\"}[1m])",
     "legendFormat": "Drops: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_errs_total{job=\"$job\",device=~\"$lan_interface\"}[1m])",
     "legendFormat": "Errors: {{ device }}"
    }
   ]
  },
  { "title": "WireGuard Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "WireGuard In/Out",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"$job\",device=~\"$wg_interface\"}[1m])",
     "legendFormat": "In: {{ device }}"
    },
    {
     "expr": "-irate(node_network_transmit_bytes_total{job=\"$job\",device=~\"$wg_interface\"}[1m])",
     "legendFormat": "Out: {{ device }}"
    }
   ]
  },
  {
   "title": "🔽 WG IN (wg0)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=~\"$job\",device=~\"$wg_interface\"}[$__rate_interval])*8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🔼 WG OUT (wg0)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=~\"$job\",device=~\"$wg_interface\"}[$__rate_interval])*8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WG Transmit Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets_total{job=\"$job\",device=~\"$wg_interface\"}[1m])",
     "legendFormat": "Transmit {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_multicast_total{job=\"$job\",device=~\"$wg_interface\"}[1m])",
     "legendFormat": "Multicasts: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{job=\"$job\",device=~\"$wg_interface\"}[1m])",
     "legendFormat": "Drops: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{job=\"$job\",device=~\"$wg_interface\"}[1m])",
     "legendFormat": "Errors: {{ device }}"
    }
   ]
  },
  {
   "title": "📶 Traffic / hour (wg0)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{job=\"$job\",device=\"$wg_interface\"}[60m])",
     "legendFormat": "{{device}}_Tx"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{job=\"$job\",device=\"$wg_interface\"}[60m])",
     "legendFormat": "{{device}}_Rx"
    }
   ]
  },
  {
   "title": "WG Receive Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{job=\"$job\",device=~\"$wg_interface\"}[1m])",
     "legendFormat": "Receive: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_multicast_total{job=\"$job\",device=~\"$wg_interface\"}[1m])",
     "legendFormat": "Multicasts: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_drop_total{job=\"$job\",device=~\"$wg_interface\"}[1m])",
     "legendFormat": "Drops: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_errs_total{job=\"$job\",device=~\"$wg_interface\"}[1m])",
     "legendFormat": "Errors: {{ device }}"
    }
   ]
  }
 ]
}